### PR TITLE
Revert "Patch 1"

### PR DESCRIPTION
**Pull request by nlmupdy01**
AWS-User-Group-Jaipur-Rajasthan/HallOfTechies#192

### CODE REVIEW

**Comment by nlmupdy01** [comment]
#224

**Comment by nlmupdy01** [comment]
Why not uploaded my profile sir please help and guide me

**Review by nlmupdy01 — COMMENTED** [review]
#235

**Comment by aksh-22** [comment]
maybe you did not entered correct data , re upload the data and make sure it follows all rules.

**Comment by nlmupdy01** [comment]
now I'm uploaded data in path  Src /upload/data.js

**Comment by nlmupdy01** [comment]
#234

**Comment by aksh-22** [comment]
it has been uploaded , go and check it.

**Comment by nlmupdy01** [comment]
yes thanks a lot actually Github I'm only for use Download Tools so no more
knowledge I using first time especially thanks for helping me ☺☺☺🙏🙏🙏

**Pull request closed without merging**
